### ISSUE TITLE
Make it easy for the user, not hard

### ISSUE THREAD

**Issue by casper** [Ayms/bitcoin-transactions#2]
Thanks for this tool, but why did you make it harder for the user than it needs to be? This stuff is complicated enough already. Some thoughts below:

Why make the user calculate amount+dev fees+network fees? 
To make a user friendly command-line tool you have to think about what the user wants to do:

1) Spend specific amount of coins from a specific address
2) Decide their network fee

The program should do the rest. Don't make the user be the computer, when the computer should be doing work for the user.

Therefore the UI should be:   
 ```
node tx.js BTG create .... amount=<amount to spend> fee=<satoshis per byte>
```

The tool should calculate the rest itself. Don't make the user calculate things that the computer can do by itself. Or am I missing something? Thanks!!

**Comment by Ayms** [comment]
Thinking about it indeed, but this is how bitcoin-cli works (the basic thinking is "if people know how to use bitcoin-cli then they know how to use bitcoin-transactions", but maybe wrong and/or excluding people that would like to use it), and I don't like it, mainly because you can't choose the network fees with bitcoin-cli

amount+dev fees+network fees=prevamount is supposed to be a simple calculation but in practice this is not so easy to compute (even myself don't find it very convenient), that's why I added warnings and checks/infos https://github.com/Ayms/bitcoin-transactions/commit/e67cb06df6a05c4a0d42ac0f92b8fd7d0c587c92

Maybe you saw #1 , I don't want people to make mistake with this module, as you can see if they make a mistake the coins go to the network, not myself, which maybe is not the correct option since it's easier for me to refund them if something wrong happens

The stupid issue are the dev fees, which as explained can easily compensate the network fees, but then a fee=<> option is not so trivial

I have to think about it, I think indeed that there should be a fee=<> option and if someone makes a mistake, or just want to test the module with a small amount, then there should be a third output to refund the delta to the spending address (ie himself)

Ideas/suggestions welcome, incentive to go further is really if people are interested, thanks for your message

**Comment by casper** [comment]
Thanks for the explanation. Yeah I saw #1 and that's where my thoughts came from. You already had one guy who was about to make a mistake because of the calculation.

Can you explain why the dev fees are a problem? That's something I did not understand quite yet. How do the dev fees relate to the network fees? Aren't those two completely separate things?

I.e. my understanding is the network fee is used to incentivize the miners to include the transaction in the next block. What has the dev fee got to do with that? Isn't it just an extra payment for the work that went into this tool?

**Comment by Ayms** [comment]
Yes, the network fees are the incentive for nodes to relay and include your transaction in a block

The calculation is quite simple but if I add a fee option then you still need to calclulate the dev fees (0.78%) and at the end there might be some satoshis floating around, that will be refunded to the spending address, and maybe will remain stuck there forever, since the amount can be too low to spend

Maybe some more feedback would be needed, as I see it if you use this module this is to spend the complete previous output, sending it  to you, to an exchange, but maybe people want the possibility to spend part of it, what do you think?

Maybe I could add a testamount command with fee=<> to make things easier then people can caclulate the correct amount to spend and eventually the one that will be refunded

**Comment by casper** [comment]
Yeah I realized what the problem was later, after I posted my question. There are actually several problems. So I kind of get it now why the original command was implemented the way it was.

PayPal and banks have a similar problem. When the user says he wants to send a certain amount, there is always a warning that there is a fee associated with that amount. Either the sender pays the fee, or the receiver. In the case the receiver pays the fee, then the amount deducted from the account will be the same as the "send amount". In the case that the sender pays the fee, then the amount deducted from the account will be "send amount" + "fee". There is a similar issue here: what do you want to deduct from the "account" in total, and how do you want the fees to be handled?

I like the idea of a `testamount` command. This is along the lines of what I was thinking too, once I realized the problem was not as simple as I assumed initially :) That way you can print out a clear breakdown of what is happening, and it makes it easier for the user to get the final parameters correct. Then add the `testamount` command as the first step in the tutorial documentation. I think it might reduce the confusion and possibilities for mistakes that way.

Anyway. It's just a suggestion. Now I understand the problem better, but perhaps such a "calculator" function like `testamount`, and an example in the docs, could make it easier for new users. I know I would need a calculator myself otherwise, because with the dev fee, it's not possible to calculate the proper end result in your head.

**Comment by Ayms** [comment]
I will implement the testamount feature, fees will at the end be slightly adjusted so there are no satoshis left

I could foresee to refund the delta to a different address than the spending one chosen by the user but I think that this is opening the door to other mistakes (opinion?), thanks for your inputs

**Comment by casper** [comment]
What do you mean by "...fees will be adjusted so there are no satoshis left", and "refund the delta"?
What is the delta, and why do you need to adjust the fees?

**Comment by Ayms** [comment]
adjusted=numbers are rounded when applying for example 0.78
delta=refund prevamount - amount - all fees if not null

**Comment by casper** [comment]
Ok. So this delta thing again proves this is extremely complicated for a newbie. Let's see if I get this. You mean the change that is left over from prevamount HAS to be sent somewhere? Kind of like the change address in the bitcoin-qt client?

If that is so, then your tool should not allow transfers of anything else than the full amount in my opinion. Or then implement another command for partial transfers and change addresses. 

Otherwise you cannot advertise this tool as en end-user tool to recover BTC fork tokens. It becomes an expert tool only for experienced users. 

If this tool is meant for recovery or transfer of fork tokens, then to avoid the mess with change addresses I would make it so it forces you to transfer the full amount always.

But I might have misunderstood what you mean by delta. If there are this many variables and concepts to understand, it would be great if they were all enumerated and explained in the documentation. 

Sorry to be a pain in the butt for you :-/, but either this tool is meant for more end user types, and you need better docs or simpler UI, or it is meant for experts only and even then I think you probably will need to document in more detail what is going on.

So: a) simple UI means you can also have simple docs, or b) complex UI with lot of options and possibilities for errors -> meticulous documentation.

**Comment by casper** [comment]
But in any case I think the `testamount` command will be useful. That sounds like a good idea in any scenario, and maybe is enough to help understand everything better.

**Comment by Ayms** [comment]
It's not so complicated and will document it accordingly, currently doing testamount but apparenly there is an issue with the signatures also, the delta is just the part that is not spent minus the fees that is refunded to the initial spending address, this is not intended for experts

**Comment by Ayms** [comment]
signatures corrected, testamount implemented, fees parameter added, doc updated, please let me know if something is unclear

**Comment by casper** [comment]
I like the detailed output of the testamount command. That helps a lot I think. With also the additional examples in the docs, should make it less likely for people to goof up now. Nice job.

**Comment by Ayms** [comment]
Thanks, I have added the "easy way" too https://github.com/Ayms/bitcoin-transactions#the-easy-way where you don't have to compute the amount at all

Then closing this one
