### ISSUE TITLE
MultiSig wallet BTG transaction error

### ISSUE THREAD

**Issue by ondrique** [Ayms/bitcoin-transactions#5]
Hi,

thank you for this great script. I am using it to get my BTG out of Multisig Electrum wallet.

I managed to create 3 successful transactions, 3 more to be done. Unfortunately, all remaining 3 get rejected when sending them to the network.

The error I get when trying to broadcast the body via https://btgexplorer.com/tx/send is:

16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation). Code:-26

When I send them with the script, it gets rejected too. 

One of the tranasctions:

```
node tx.js BTG create prevtx=57b3cadfdb1ed2c24404db6b8b96afaa4b8ce2f7ef64836a5f9245fd32a
51df5 prevaddr=3GauZViffpjJxZnNjw8WYS4NRuegkxdKvX prevamount=0.02477516 previndex=1 privkey=[key1]-[key2]-[redeem]-2of3 addr=GeLviuVRCnzFD2PvTRUPJPwjaCjzwg5CDc fees=0.00001
```

Let me know what info would you need to inspect the problem, thank you for your help and time.

Ondrej

**Comment by Ayms** [comment]
Hi, thanks, the transaction looks correct, the message means that the signatures are not, are you sure that you are using the correct privkeys and redeem script?

I just realized that I forgot to implement a decoderedeem command to display the pubkeys so you can find the correct associated privkeys, going to do it now

If you are sure about the privkeys thanks to email me the log of the above create command, there are no sensitive info in there but still better that I get it in private

**Comment by Ayms** [comment]
I just added decoderedeem https://github.com/Ayms/bitcoin-transactions#multisig-wallets-2

Maybe check this first

**Comment by ondrique** [comment]
Thank you for that, I rechecked everything multiple times, the keys should be correct. I have just sent you an email.

**Comment by Ayms** [comment]
Thanks for the logs and try of decoderedeem

Everything looks good: you have the right privkeys corresponding to the redeem pubkeys, if not the tx would not be verified, and the parameters correspond to the output that you are trying to spend, so on your side everything is OK

Conclusion: there is still a bug in the tool with the signatures, strange because I made plenty of transactions without pb, please let me see and correct this

**Comment by ondrique** [comment]
Thank you! 

One thing I noticed, most probably unrelated to this issue. 

Fees differ slightly differ in the log. 

At the beginning of the output, there is:

```
--- Network fees are: 0.00001000
--- Dev fees are: 0.00532971
```

and later on below:

```
Network Fees: 1001 - 2.52 satoshis/byte
Dev Fees: 532970
```

Thanks!

**Comment by Ayms** [comment]
Yes, there is always a satoshi "floating around" (a bit like with VAT if you know this :-) ) due to a rounding issue, I will not correct it since it's very minor and I would have to change/retest all the test vectors

Unfortunately it seems to be more complicate, probably the signature scheme does not respect one of the rules of bitcoin code

**Comment by Ayms** [comment]
https://github.com/bitcoin/bitcoin/issues/11891

**Comment by ondrique** [comment]
Sorry to hear that. 

If you would need any assistance, pls let me know.

**Comment by Ayms** [comment]
Corrected https://github.com/Ayms/bitcoin-transactions/commit/64feb7937f9a798775abdfd4e695f035fc4095b7

Signatures were correct but not correctly ordered in scriptsig

@ondrique thanks again for your help

**Comment by ondrique** [comment]
Thank you!
